drop table if exists quizAnswer;
drop table if exists quizQuestion;
drop table if exists quiz;
CREATE TABLE if not exists userQuiz
(
    chatId                 int,
    currentQuizId          int,
    nextStepQuizQuestionId int,
    primary key (chatId)
);

CREATE TABLE if not exists quiz
(
    id    int generated by default as identity primary key,
    title varchar(250) not null

);


CREATE TABLE if not exists quizQuestion(
    id int generated by default as identity primary key,
    quizId int references quiz (id) not null ,
    questionText varchar(250) not null,
    step int not null
);

CREATE TABLE if not exists quizAnswer(
    id int generated by default as identity primary key,
    quizQuestionId int references quizQuestion (id) not null,
    answerText varchar(250) not null,
    resultText varchar(250) not null,
    isCorrectAnswer boolean not null default false
);
UPDATE userquiz set nextstepquizquestionid=null,currentquizid=null;